pi19lanchonete/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from core.views import index, menu, fazer_pedido, signup, login, perfil, cadastroPrato, dados, sobre, pratos, excluir, ListaPedidos, cadastroCategoria, pedidos, editar


urlpatterns = [
	path('index/', index, name='index'),
	path('menu/', menu, name= 'menu'),
	path('pedido/', fazer_pedido, name = 'pedido'),
    path('sobre/', sobre, name='sobre'),
    path('perfil/', perfil, name = 'perfil'),
    path('', include('allauth.urls')),
    path('pratos/', pratos, name = 'pratos'),
    path('pedidos/', pedidos, name='pedidos'),
    path('ListaPedidos/', ListaPedidos, name = 'ListaPedidos'),
    path('cadastroPrato/', cadastroPrato, name = 'cadastroPrato'),
    path('cadastroCategoria/', cadastroCategoria, name = 'cadastroCategoria'),
    path('dados/<int:id>/', dados, name='dados'), 
    path('excluir/<int:id>/', excluir, name="excluir"),
    path('editar/<int:id>/', editar, name="editar"),
    # path('carrinho/adicionar/<int:produto_id>/', adicionar_ao_carrinho, name='carrinho_adicionar'),
    # path('carrinho/adicionar/<int:produto_id>/', remover_do_carrinho, name='carrinho_remover'),
    # path('carrinho/', carrinho, name='carrinho'),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
	email = models.CharField('email', max_length=254)
	endereco = 	models.CharField('endereco', max_length = 254)
	ncasa = models.CharField('ncasa', max_length = 6)
	cep = models.CharField('cep', max_length = 8)
	telefone = models.CharField('telefone', max_length = 9)	
	cpf = models.CharField('CPF', max_length = 11)
	foto = models.ImageField('foto', upload_to = 'media/')
	def __str__(self):
		return self.cpf


class categoria(models.Model):
	nome = models.CharField('nome', max_length=100)
	
	def __str__(self):
		return self.nome

class produto(models.Model):
	nome = models.CharField('nome', max_length=100)
	descricao = models.CharField('descricao', max_length=500)
	imagem = models.ImageField('imagem', upload_to='media/', max_length=100)
	preco = models.DecimalField('preco', max_digits=5, decimal_places=2, null = True) 
	categoria = models.ForeignKey(categoria, on_delete=models.CASCADE )

	def __str__(self):
		return self.nome

class pedido(models.Model):
	quantidade = models.IntegerField('quantidade', null=True)
	tempo = models.DateTimeField('tempo', auto_now=True, auto_now_add=False)
	produto = models.ForeignKey(produto, on_delete=models.CASCADE)
	cliente = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
	etapa = models.PositiveSmallIntegerField('Etapa', default=0)

	def __str__(self):
		return '%s x %s' % (self.produto, self.quantidade)


	
#class avaliacao(models.Model):
# Create your models here.

core/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import produto, pedido, categoria, CustomUser

class CustomUserCreationForm(UserCreationForm):
	class Meta:
		model = CustomUser

		fields = ('username', 'email', 'endereco', 'ncasa', 'cep', 'telefone', 'cpf', 'foto')

class CustomUserChangeForm(UserChangeForm):
	class Meta:
		model = CustomUser
		fields = ('username', 'email', 'endereco', 'ncasa', 'cep', 'telefone', 'cpf', 'foto')

class produtoForm(ModelForm):
	class Meta:
		model = produto
		fields = ['nome', 'preco', 'imagem', 'descricao', 'categoria'] 

class pedidoForm(ModelForm):
	class Meta:
		model = pedido
		fields = ['quantidade']

class categoriaForm(ModelForm):
	class Meta:
		model = categoria
		fields = ['nome']

core/views.py
from django.shortcuts import render, redirect
from django.db.models import Sum
from django.forms.models import model_to_dict
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.decorators import login_required
from .models import produto, categoria, pedido, CustomUser
from .forms import produtoForm, categoriaForm, CustomUserChangeForm

def index(request):
    categorias = categoria.objects.all()
    contexto = {
        'categorias': categorias
    }
    return render(request, 'index.html', contexto)

def menu(request):
    return render(request, 'menu.html')

def fazer_pedido(request):
    if not request.user.is_authenticated:
        return redirect('account_login')
    total = 0
    if request.method == 'POST':
        pedidos = {k.strip('pedido-'):int(v) for k, v in request.POST.items() if k.startswith('pedido') and v}
        if not pedidos:
        	return redirect('index')
        for id, quant in pedidos.items():
            p = produto.objects.get(pk=id)
            pedido.objects.create(
                produto=p,
                quantidade=quant,
                cliente=request.user
            )
            total += p.preco * quant
    contexto = {
        'pedidos': pedidos,
        'total': total
        }        
    return render(request, 'pedido.html', contexto)


def ListaPedidos(request):
    pedidos = pedido.objects.filter(cliente=request.user)
    total = pedidos.aggregate(Sum('produto__preco'))
    contexto = {
        'pedidos': pedidos,
        'total': total['produto__preco__sum'],
    }
    return render(request, 'ListaPedidos.html', contexto)


def pedidos(request):
    pedidos = pedido.objects.filter(etapa=0)
    contexto = {
        'pedidos': pedidos
    }
    return render(request, 'pedidos.html', contexto)

def sobre(request):
    return render(request, 'sobre.html')


def pratos(request):
    categorias = categoria.objects.all()
    contexto = {
    'categorias': categorias
    }
    return render(request, 'pratos.html', contexto) 

def signup(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('login')
    contexto = {
    'form': form
    }   
    return render(request, 'account/cadastro.html', contexto)

def cadastroPrato(request):
    
    form = produtoForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()     
        return redirect('perfil')       
    contexto = {
        'form': form
    }
    
    return render(request, 'cadastroPrato.html', contexto)

def cadastroCategoria(request):
    
    form = categoriaForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        categoria = form.save(commit=False)     
        categoria.save()
        return redirect('perfil')       
    contexto = {
        'form': form
    }
    
    return render(request, 'cadastroCategoria.html', contexto)  

def login(request):
    return render(request, 'login.html')

@login_required
def perfil(request):
    return render(request, 'perfil.html')

@login_required
def dados(request, id):
    user = CustomUser.objects.get(pk=id)
    form = CustomUserChangeForm(request.POST or None, instance=user)
    if form.is_valid():
        form.save()
        return redirect('perfil')
    contexto = {
    'form': form
    }
    return render(request, 'account/editardados.html', contexto)

def excluir(request, id):
    p = produto.objects.get(pk=id)
    p.delete()
    return redirect('pratos')

def editar(request, id):
    p = produto.objects.get(pk=id)

    form = produtoForm(request.POST or None, instance=p)

    if form.is_valid():
        form.save()
        return redirect('pratos')

    contexto = {
        'form': form
    }
    return render(request, 'cadastroPrato.html', contexto)

core/templates/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Tasty - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">

    <link rel="stylesheet" href="css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="css/animate.css">
    
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">

    <link rel="stylesheet" href="css/aos.css">

    <link rel="stylesheet" href="css/ionicons.min.css">

    <link rel="stylesheet" href="css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="css/jquery.timepicker.css">

    
    <link rel="stylesheet" href="css/flaticon.css">
    <link rel="stylesheet" href="css/icomoon.css">
    <link rel="stylesheet" href="css/style.css">
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
      <div class="container">
        <a class="navbar-brand" href="index.html">Tasty</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a href="index.html" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="menu.html" class="nav-link">Menu</a></li>
            <li class="nav-item"><a href="specialties.html" class="nav-link">Specialties</a></li>
            <li class="nav-item"><a href="reservation.html" class="nav-link">Reservation</a></li>
            <li class="nav-item"><a href="blog.html" class="nav-link">Blog</a></li>
            <li class="nav-item active"><a href="about.html" class="nav-link">About</a></li>
            <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- END nav -->
    
    <section class="home-slider owl-carousel">
      <div class="slider-item" style="background-image: url('images/bg_1.jpg');" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
          <div class="row slider-text align-items-center justify-content-center">
            <div class="col-md-10 col-sm-12 ftco-animate text-center">
              <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>About</span></p>
              <h1 class="mb-3">About Us</h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    <section class="ftco-section-2">
      <div class="container d-flex">
        <div class="section-2-blocks-wrapper row">
          <div class="img col-sm-12 col-lg-6" style="background-image: url('images/about-2.jpg');">
          </div>
          <div class="text col-lg-6 ftco-animate">
            <div class="text-inner align-self-start">
              <span class="subheading">About Tasty</span>
              <h3 class="heading">Our chef cooks the most delicious food for you</h3>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>

              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <div class="ftco-section">
      <div class="container">
        <div class="row justify-content-center mb-5 pb-5">
          <div class="col-md-7 text-center heading-section ftco-animate">
            <span class="subheading">Our Chef</span>
            <h2>Our Master Chef</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 ftco-animate">
            <div class="block-10">
              <div class="person-info">
                <span class="name">Thomas Smith</span>
                <span class="position">Head Chef</span>
              </div>
              <div class="chef-img" style="background-image: url(images/chef-1.jpg)"></div>
            </div>
          </div>
          <div class="col-md-4 ftco-animate">
            <div class="block-10">
              <div class="person-info">
                <span class="name">Francis Gibson</span>
                <span class="position">Assistant Chef</span>
              </div>
              <div class="chef-img" style="background-image: url(images/chef-2.jpg)"></div>
            </div>
          </div>
          <div class="col-md-4 ftco-animate">
            <div class="block-10">
              <div class="person-info">
                <span class="name">Angelo Maestro</span>
                <span class="position">Assistant Chef</span>
              </div>
              <div class="chef-img" style="background-image: url(images/chef-3.jpg)"></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <section class="instagram">
      <div class="container-fluid">
        <div class="row no-gutters justify-content-center pb-5">
          <div class="col-md-7 text-center heading-section ftco-animate">
            <h2><span>Instagram</span></h2>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-sm-12 col-md ftco-animate">
            <a href="images/insta-1.jpg" class="insta-img image-popup" style="background-image: url(images/insta-1.jpg);">
              <div class="icon d-flex justify-content-center">
                <span class="icon-instagram align-self-center"></span>
              </div>
            </a>
          </div>
          <div class="col-sm-12 col-md ftco-animate">
            <a href="images/insta-2.jpg" class="insta-img image-popup" style="background-image: url(images/insta-2.jpg);">
              <div class="icon d-flex justify-content-center">
                <span class="icon-instagram align-self-center"></span>
              </div>
            </a>
          </div>
          <div class="col-sm-12 col-md ftco-animate">
            <a href="images/insta-3.jpg" class="insta-img image-popup" style="background-image: url(images/insta-3.jpg);">
              <div class="icon d-flex justify-content-center">
                <span class="icon-instagram align-self-center"></span>
              </div>
            </a>
          </div>
          <div class="col-sm-12 col-md ftco-animate">
            <a href="images/insta-4.jpg" class="insta-img image-popup" style="background-image: url(images/insta-4.jpg);">
              <div class="icon d-flex justify-content-center">
                <span class="icon-instagram align-self-center"></span>
              </div>
            </a>
          </div>
          <div class="col-sm-12 col-md ftco-animate">
            <a href="images/insta-5.jpg" class="insta-img image-popup" style="background-image: url(images/insta-5.jpg);">
              <div class="icon d-flex justify-content-center">
                <span class="icon-instagram align-self-center"></span>
              </div>
            </a>
          </div>
        </div>
      </div>
    </section>

    <footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Tasty</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Opening Hours</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">Monday: <span>08: - 22:00</span></a></li>
                <li><a href="#" class="py-2 d-block">Tuesday: <span>08: - 22:00</span></a></li>
                <li><a href="#" class="py-2 d-block">Wednesday: <span>08: - 22:00</span></a></li>
                <li><a href="#" class="py-2 d-block">Thursday: <span>08: - 22:00</span></a></li>
                <li><a href="#" class="py-2 d-block">Friday: <span>08: - 22:00</span></a></li>
                <li><a href="#" class="py-2 d-block">Saturday: <span>08: - 22:00</span></a></li>
                <li><a href="#" class="py-2 d-block">Sunday: <span>08: - 22:00</span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Contact Information</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">198 West 21th Street, Suite 721 New York NY 10016</a></li>
                <li><a href="#" class="py-2 d-block">+ 1235 2355 98</a></li>
                <li><a href="#" class="py-2 d-block">info@yoursite.com</a></li>
                <li><a href="#" class="py-2 d-block">email@email.com</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Newsletter</h2>
              <p>Far far away, behind the word mountains, far from the countries.</p>
              <form action="#" class="subscribe-form">
                <div class="form-group">
                  <span class="icon icon-paper-plane"></span>
                  <input type="text" class="form-control" placeholder="Subscribe">
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="js/jquery.min.js"></script>
  <script src="js/jquery-migrate-3.0.1.min.js"></script>
  <script src="js/popper.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/jquery.easing.1.3.js"></script>
  <script src="js/jquery.waypoints.min.js"></script>
  <script src="js/jquery.stellar.min.js"></script>
  <script src="js/owl.carousel.min.js"></script>
  <script src="js/jquery.magnific-popup.min.js"></script>
  <script src="js/aos.js"></script>
  <script src="js/jquery.animateNumber.min.js"></script>
  <script src="js/bootstrap-datepicker.js"></script>
  <script src="js/jquery.timepicker.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="js/google-map.js"></script>
  <script src="js/main.js"></script>
    
  </body>
</html>

templates/ListaPedidos.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
<html>
<head>
	<title></title>
</head>
<body>
{% block conteudo %}
	{% for pedido in pedidos %}
		{{pedido}}
	{% endfor %}
	Valor total: {{total|floatformat:2}}
{% endblock %}
</body>
</html>

templates/cadastroCategoria.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
<html>
<head>
	<title></title>
</head>
<body>
{% block conteudo %}
<br />
<br />
<div class="row">
      <div class="col-lg-12 mb-12">
        
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
        <div class="controls text-center">
            <h2>Categoria: </h2> 
            <br />
            <p>{{form.nome}}</p>
            <button type="submit" class="btn btn-primary" id="sendMessageButton">Salvar</button>
        </div>
	</form>
    </div>
  </div>    
    
{% endblock %}
</body>
</html>

templates/cadastroPrato.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
<html>
<head>
  <title></title>
</head>
<body>

{% block conteudo %}
  
{% if user.is_superuser %}
 <br />
 <div class="row">
      <div class="col-lg-12 mb-12 text-center">
        <h2>Prato: </h2>
        <br />
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
        <div class="controls">
            <label>Imagem: </label> 
            <p>{{form.imagem}}</p>              
        </div>
    
	<div class="control-group form-group">
        <div class="controls">
            
            <label>Nome do Prato: </label> 
            <p>{{form.nome}}</p>              
        </div>
    </div>
    <div class="control-group form-group">
        <div class="controls">
            
            <label>Preço: </label> 
            <p>{{form.preco}}</p>              
        </div>
    </div>
    <div class="control-group form-group">
        <div class="controls">
            
            <label>Descrição do Prato: </label> 
            <p>{{form.descricao}}</p>              
        </div>
    </div>
    <div class="control-group form-group">
        <div class="controls">
            
            <label>Categoria: </label> 
            <p>{{form.categoria}}</p>              
        </div>
    </div>
    <button type="submit" class="btn btn-primary" id="sendMessageButton">Salvar</button>
  </form>  
</div>
</div>
{%endif%}

{% endblock %}

</body>
</html>

<!-- Botão de cadastro -->
 

templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

<html>
<head>
  <title>Home</title>
</head>
<body>
  {% block conteudo %}
    <br/>
    <br/>
    <section class="ftco-section-2">
      <div class="container d-flex">
        <div class="section-2-blocks-wrapper row">
          <div class="img col-sm-12 col-lg-4" style="background-image: url('{% static "images/lanchonetecop.jpg" %}');">
          </div>
          <div class="text col-lg-8 ftco-animate">
            <div class="text-inner align-self-start">
              <span class="subheading">Sobre a Lanchonete Da Hora</span>
              <h3 class="heading">Os mais deliciosos lanches da região para você!</h3>
              <p>A lanchonete da Hora é rica em uma variedade salgados, doces e bebidas. Além disso, estamos sempre preocupados com a sua satisfação e o seu bolso. É você comendo bem sem gastar muito.</p>

              <p>ESCOLHA O SEU E DEGUSTE!</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section bg-light">
      <div class="container">
        <div class="row justify-content-center mb-5 pb-5">
          <div class="col-md-7 text-center heading-section ftco-animate">
            <h2>MENU</h2>
          </div>
        </div>
        <form action="/pedido/" method="POST">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-12 dish-menu">

              <div class="nav nav-pills justify-content-center ftco-animate" id="v-pills-tab" role="tablist" aria-orientation="vertical">
              
                {% for categoria in categorias %}
                <a class="nav-link py-3 px-4 {% if forloop.first %}active{% endif %}" id="categoria-{{categoria.id}}-tab" data-toggle="pill" href="#categoria-{{categoria.id}}" role="tab" aria-controls="categoria-{{categoria.id}}" aria-selected="false">{{categoria.nome}}</a>
                {% endfor %}
              </div>

              <div class="tab-content py-5" id="v-pills-tabContent">
                {% for categoria in categorias %}
                  <div class="tab-pane fade show {% if forloop.first %}active{% endif %}" id="categoria-{{categoria.id}}" role="tabpanel" aria-labelledby="categoria-{{categoria.id}}-tab">
                    {% for produto in categoria.produto_set.all %}
                      <div class="row">
                        <div class="menus d-flex ftco-animate">
                          <div class="menu-img" style="background-image: url('/media/{{produto.imagem}}');">
                          </div>
                          <div class="text d-flex">
                            <div class="one-half">
                              <h3>{{produto.nome}}</h3>
                              <p>{{produto.descricao}}</p>
                            </div>
                            <div class="one-forth">
                              <span class="price">{{produto.preco}}</span>
                              <input type="number" name="pedido-{{produto.id}}" class="w-100" placeholder="Quantidade" />
                            </div>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                  </div>
                {% endfor %}
              </div>
            </div>
          </div>
          {% if not user.is_superuser %} 
          <div class="col-sm-12 pt-4 text-center ftco-animate">
            {% if user.is_authenticated %}
            <span><button type="submit" class="btn btn-primary btn-outline-primary p-3">FAÇA UM PEDIDO</button></span>
            {% else %}
            <span><a  href="{% url 'account_login' %}" type="submit" class="btn btn-primary btn-outline-primary p-3">LOGIN</a></span>
            {% endif %}
          </div>
          {% endif %}
        </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  {% endblock %}
  </body>
</html>

templates/pedidos.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block conteudo %}
<<<<<<< HEAD
	{% regroup pedidos by cliente as clientes %}
=======
	<br />
	<div class="text-center">
        <h2>Pedidos: </h2> 
    </div>
>>>>>>> f9d5690d13417d9b6415ebacaf6216a5bb5b1c6f
	<ul>
		{% for cliente in clientes %}
			<li>{{cliente.grouper.username}} - {{cliente.grouper.telefone}}</li>
				<ul>	
					{% for pedido in cliente.list %}
						<li>{{pedido.produto.nome}} - {{pedido.quantidade}}</li>
					{% endfor %}
				</ul>
		{% endfor %}
	</ul>
{% endblock %}

templates/pratos.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
<html>
<head>
	
</head>
<body>
{% block conteudo %}	
<div class="container">

    <div class="row">

      <div class="col-lg-4">
        <h1 class="my-5">Lista de Pratos</h1>
        <div class="list-group">
        {% for categoria in categorias %}
          {{categoria.nome}}
          {% for produto in categoria.produto_set.all %}
            <p class="list-group-item mb-3">{{produto.nome}} <a class="float-right" href="{% url 'excluir' produto.id %}">Apagar</a> <a class="float-right" href="{% url 'editar' produto.id %}">Editar</a></p>
          {% endfor %}
        {% empty %}
          <p>Nenhum produto cadastrado</p>
        {% endfor %}  
        </div>
          <br />
          <span><a href="{% url 'cadastroCategoria' %}" class="btn btn-primary btn-outline-primary p-3">Cadastrar Categoria</a></span>
          <span><a href="{% url 'cadastroPrato' %}" class="btn btn-primary btn-outline-primary p-3">Cadastrar Prato</a></span>
      </div>
      <!-- /.col-lg-3 -->
      
    </div>
  </div>
 {% endblock %}
</body>
</html>